// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prismaDmob/schema.prisma",
  datasource: {
    url: process.env["DMOB_DATABASE_URL"],
  },
});
