export const EnvKeys = {
  LOG_LEVEL: "LOG_LEVEL",
  RPC_URL: "RPC_URL",
  CHAIN_ID: "CHAIN_ID",
  APP_PORT: "APP_PORT",
  CDP_SERVICE_URL: "CDP_SERVICE_URL",
  URL_FINDER_SERVICE_URL: "URL_FINDER_SERVICE_URL",
  URL_FINDER_AUTH_TOKEN: "URL_FINDER_AUTH_TOKEN",
  EVIDENCE_BATCH_SIZE: "EVIDENCE_BATCH_SIZE",

  POREP_SERVICE_ROLE_WALLET_PK: "POREP_SERVICE_ROLE_WALLET_PK",
  ORACLE_ROLE_WALLET_PK: "ORACLE_ROLE_WALLET_PK",
  TERMINATION_ORACLE_ROLE_WALLET_PK: "TERMINATION_ORACLE_ROLE_WALLET_PK",
  FILECOIN_PAY_ROLE_WALLET_PK: "FILECOIN_PAY_ROLE_WALLET_PK",

  JOB_TRIGGER_AUTH_TOKEN: "JOB_TRIGGER_AUTH_TOKEN",

  TRIGGER_SLI_JOB_INTERVAL_CRON: "TRIGGER_SLI_JOB_INTERVAL_CRON",
  TRIGGER_CLAIMS_TRACKING_JOB_INTERVAL_CRON:
    "TRIGGER_CLAIMS_TRACKING_JOB_INTERVAL_CRON",
  TRIGGER_SETTLEMENT_BOT_JOB_INTERVAL_CRON:
    "TRIGGER_SETTLEMENT_BOT_JOB_INTERVAL_CRON",
  TRIGGER_TERMINATE_DEAL_JOB_INTERVAL_CRON:
    "TRIGGER_TERMINATE_DEAL_JOB_INTERVAL_CRON",
  TRIGGER_SYNC_DEALS_JOB_INTERVAL_CRON: "TRIGGER_SYNC_DEALS_JOB_INTERVAL_CRON",
  SYNC_URL_FINDER_SLI_TARGETS_JOB_INTERVAL_CRON:
    "SYNC_URL_FINDER_SLI_TARGETS_JOB_INTERVAL_CRON",
  TRIGGER_END_EPOCH_DEAL_JOB_INTERVAL_CRON:
    "TRIGGER_END_EPOCH_DEAL_JOB_INTERVAL_CRON",
  TRIGGER_REJECT_EXPIRED_DEAL_INTERVAL_CRON:
    "TRIGGER_REJECT_EXPIRED_DEAL_INTERVAL_CRON",
  TRIGGER_REFRESH_EVIDENCE_STATUS_INTERVAL_CRON:
    "TRIGGER_REFRESH_EVIDENCE_STATUS_INTERVAL_CRON",

  SLI_ORACLE_CONTRACT_ADDRESS: "SLI_ORACLE_CONTRACT_ADDRESS",
  DATACAP_EVIDENCE_ADAPTER_CONTRACT_ADDRESS:
    "DATACAP_EVIDENCE_ADAPTER_CONTRACT_ADDRESS",
  POREP_MARKET_CONTRACT_ADDRESS: "POREP_MARKET_CONTRACT_ADDRESS",
  SP_REGISTRY_CONTRACT_ADDRESS: "SP_REGISTRY_CONTRACT_ADDRESS",
  FILECOIN_PAY_CONTRACT_ADDRESS: "FILECOIN_PAY_CONTRACT_ADDRESS",
  SLI_SCORER_CONTRACT_ADDRESS: "SLI_SCORER_CONTRACT_ADDRESS",
  CLAIM_INSPECTOR_CONTRACT_ADDRESS: "CLAIM_INSPECTOR_CONTRACT_ADDRESS",
  SECTOR_STATUS_INSPECTOR_CONTRACT_ADDRESS:
    "SECTOR_STATUS_INSPECTOR_CONTRACT_ADDRESS",
} as const;

type EnvKey = (typeof EnvKeys)[keyof typeof EnvKeys];

export const SERVICE_CONFIG: Record<EnvKey, string> = {
  LOG_LEVEL: process.env.LOG_LEVEL || "info",
  SLI_ORACLE_CONTRACT_ADDRESS: process.env.SLI_ORACLE_CONTRACT_ADDRESS || "",
  RPC_URL: process.env.RPC_URL || "",
  CHAIN_ID: process.env.CHAIN_ID || "",
  TRIGGER_SLI_JOB_INTERVAL_CRON:
    process.env.TRIGGER_SLI_JOB_INTERVAL_CRON || "",
  TRIGGER_CLAIMS_TRACKING_JOB_INTERVAL_CRON:
    process.env.TRIGGER_CLAIMS_TRACKING_JOB_INTERVAL_CRON || "",
  TRIGGER_SETTLEMENT_BOT_JOB_INTERVAL_CRON:
    process.env.TRIGGER_SETTLEMENT_BOT_JOB_INTERVAL_CRON || "",
  TRIGGER_TERMINATE_DEAL_JOB_INTERVAL_CRON:
    process.env.TRIGGER_TERMINATE_DEAL_JOB_INTERVAL_CRON || "",
  TRIGGER_SYNC_DEALS_JOB_INTERVAL_CRON:
    process.env.TRIGGER_SYNC_DEALS_JOB_INTERVAL_CRON || "",
  SYNC_URL_FINDER_SLI_TARGETS_JOB_INTERVAL_CRON:
    process.env.SYNC_URL_FINDER_SLI_TARGETS_JOB_INTERVAL_CRON || "",
  TRIGGER_END_EPOCH_DEAL_JOB_INTERVAL_CRON:
    process.env.TRIGGER_END_EPOCH_DEAL_JOB_INTERVAL_CRON || "",
  TRIGGER_REJECT_EXPIRED_DEAL_INTERVAL_CRON:
    process.env.TRIGGER_REJECT_EXPIRED_DEAL_INTERVAL_CRON || "",
  TRIGGER_REFRESH_EVIDENCE_STATUS_INTERVAL_CRON:
    process.env.TRIGGER_REFRESH_EVIDENCE_STATUS_INTERVAL_CRON || "0 7 1 * *",
  CDP_SERVICE_URL: process.env.CDP_SERVICE_URL || "",
  URL_FINDER_SERVICE_URL:
    process.env.URL_FINDER_SERVICE_URL ||
    "https://api.staging.sp-tool.allocator.tech",
  EVIDENCE_BATCH_SIZE: process.env.EVIDENCE_BATCH_SIZE || "1000",

  URL_FINDER_AUTH_TOKEN: process.env.URL_FINDER_AUTH_TOKEN || "",
  JOB_TRIGGER_AUTH_TOKEN: process.env.JOB_TRIGGER_AUTH_TOKEN || "",
  APP_PORT: process.env.APP_PORT || "3000",
  DATACAP_EVIDENCE_ADAPTER_CONTRACT_ADDRESS:
    process.env.DATACAP_EVIDENCE_ADAPTER_CONTRACT_ADDRESS || "",
  POREP_MARKET_CONTRACT_ADDRESS:
    process.env.POREP_MARKET_CONTRACT_ADDRESS || "",
  SP_REGISTRY_CONTRACT_ADDRESS: process.env.SP_REGISTRY_CONTRACT_ADDRESS || "",
  FILECOIN_PAY_CONTRACT_ADDRESS:
    process.env.FILECOIN_PAY_CONTRACT_ADDRESS || "",
  SLI_SCORER_CONTRACT_ADDRESS: process.env.SLI_SCORER_CONTRACT_ADDRESS || "",
  CLAIM_INSPECTOR_CONTRACT_ADDRESS:
    process.env.CLAIM_INSPECTOR_CONTRACT_ADDRESS || "",
  SECTOR_STATUS_INSPECTOR_CONTRACT_ADDRESS:
    process.env.SECTOR_STATUS_INSPECTOR_CONTRACT_ADDRESS || "",

  POREP_SERVICE_ROLE_WALLET_PK: process.env.POREP_SERVICE_ROLE_WALLET_PK || "",
  ORACLE_ROLE_WALLET_PK: process.env.ORACLE_ROLE_WALLET_PK || "",
  TERMINATION_ORACLE_ROLE_WALLET_PK:
    process.env.TERMINATION_ORACLE_ROLE_WALLET_PK || "",
  FILECOIN_PAY_ROLE_WALLET_PK: process.env.FILECOIN_PAY_ROLE_WALLET_PK || "",
};
