import "dotenv/config";

export const EnvKeys = {
  LOG_LEVEL: "LOG_LEVEL",
  WALLET_PRIVATE_KEY: "WALLET_PRIVATE_KEY",
  ORACLE_CONTRACT_ADDRESS: "ORACLE_CONTRACT_ADDRESS",
  SLA_ALLOCATOR_CONTRACT_ADDRESS: "SLA_ALLOCATOR_CONTRACT_ADDRESS",
  RPC_URL: "RPC_URL",
  CHAIN_ID: "CHAIN_ID",
  TRIGGER_SLI_JOB_INTERVAL_CRON: "TRIGGER_SLI_JOB_INTERVAL_CRON",
  TRIGGER_CLAIMS_TRACKING_JOB_INTERVAL_CRON:
    "TRIGGER_CLAIMS_TRACKING_JOB_INTERVAL_CRON",
  CDP_SERVICE_URL: "CDP_SERVICE_URL",
  JOB_TRIGGER_AUTH_TOKEN: "JOB_TRIGGER_AUTH_TOKEN",
  APP_PORT: "APP_PORT",
  CLIENT_CONTRACT_ADDRESS: "CLIENT_CONTRACT_ADDRESS",
  POREP_MARKET_CONTRACT_ADDRESS: "POREP_MARKET_CONTRACT_ADDRESS",
  SP_REGISTRY_CONTRACT_ADDRESS: "SP_REGISTRY_CONTRACT_ADDRESS",
} as const;

type EnvKey = (typeof EnvKeys)[keyof typeof EnvKeys];

export const SERVICE_CONFIG: Record<EnvKey, string> = {
  LOG_LEVEL: process.env.LOG_LEVEL || "info",
  ORACLE_CONTRACT_ADDRESS: process.env.ORACLE_CONTRACT_ADDRESS || "",
  SLA_ALLOCATOR_CONTRACT_ADDRESS:
    process.env.SLA_ALLOCATOR_CONTRACT_ADDRESS || "",
  WALLET_PRIVATE_KEY: process.env.WALLET_PRIVATE_KEY || "",
  RPC_URL: process.env.RPC_URL || "",
  CHAIN_ID: process.env.CHAIN_ID || "",
  TRIGGER_SLI_JOB_INTERVAL_CRON:
    process.env.TRIGGER_SLI_JOB_INTERVAL_CRON || "",
  TRIGGER_CLAIMS_TRACKING_JOB_INTERVAL_CRON:
    process.env.TRIGGER_CLAIMS_TRACKING_JOB_INTERVAL_CRON || "",
  CDP_SERVICE_URL: process.env.CDP_SERVICE_URL || "",
  JOB_TRIGGER_AUTH_TOKEN: process.env.JOB_TRIGGER_AUTH_TOKEN || "",
  APP_PORT: process.env.APP_PORT || "3000",
  CLIENT_CONTRACT_ADDRESS: process.env.CLIENT_CONTRACT_ADDRESS || "",
  POREP_MARKET_CONTRACT_ADDRESS:
    process.env.POREP_MARKET_CONTRACT_ADDRESS || "",
  SP_REGISTRY_CONTRACT_ADDRESS: process.env.SP_REGISTRY_CONTRACT_ADDRESS || "",
};
